ALTER TABLE messages
ADD COLUMN IF NOT EXISTS max_views INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_vanishing BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'sent',
ADD COLUMN IF NOT EXISTS file_name TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS file_size BIGINT DEFAULT NULL;

ALTER TABLE conversations
ADD COLUMN IF NOT EXISTS vanish_mode_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE posts
ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';

ALTER TABLE stories
ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';
