-- 20260528000001_vanish_timer.sql
ALTER TABLE messages
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

ALTER TABLE conversations
ADD COLUMN IF NOT EXISTS vanish_timer_seconds INT DEFAULT 0;
